### ISSUE TITLE
Chrome doesn't show CJK fonts.

### ISSUE THREAD

**Issue by tabetai** [flathub/com.google.Chrome#202]
Chrome doesn't show CJK fonts, while other browsers (Firefox, Librewolf, Chromium) show them perfectly fine.

 
Fedora Linux 37.20230416.0 (Silverblue) 
Flatpak 1.14.4
GNOME 43.4

**Comment by benkei-kuruma** [comment]
Same issue here, also on Silverblue (38). Screenshot taken from YouTube, where I'm trying to search using Chinese characters.

![image](https://user-images.githubusercontent.com/22654030/232329624-3a051ff1-1d7d-44e1-8cb4-0bb2cc8e869c.png)

FWIW I notice Steam Flatpak is also having this issue.

![image](https://user-images.githubusercontent.com/22654030/232329699-f807163b-788f-496e-965f-af3fb4935255.png)

**Comment by 22p** [comment]
temporary solution 
`cp -R /usr/share/fonts/google-noto-sans-cjk-vf-fonts  ~/.var/app/com.google.Chrome/data/fonts` 
`ln -srv ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/tenfoot/resource/fonts ~/.var/app/com.valvesoftware.Steam/.fonts`

**Comment by dogs-1985** [comment]
Hi, I also have the same problem (Fedora).
This is my temporary solution, revert back to the previous version.

Google Chrome
`flatpak update --commit=1b2cabc20c6454312cb17d9c55940759ff25bbc63f7e9b2392adc1fd9136b5fe com.google.Chrome`

Microsoft Edge
`flatpak update --commit=204c1ec88ff6f562077e95a772b6b6980dd937d849c3cac69a76df3f00bb0a5f com.microsoft.Edge`

**Comment by dogs-1985** [comment]
> Same issue here, also on Silverblue (38). Screenshot taken from YouTube, where I'm trying to search using Chinese characters.
> 
> ![image](https://user-images.githubusercontent.com/22654030/232329624-3a051ff1-1d7d-44e1-8cb4-0bb2cc8e869c.png)
> 
> FWIW I notice Steam Flatpak is also having this issue.
> 
> ![image](https://user-images.githubusercontent.com/22654030/232329699-f807163b-788f-496e-965f-af3fb4935255.png)
> 
> Chinese characters appear fine in other apps, such as Text Editor:
> 
> ![image](https://user-images.githubusercontent.com/22654030/232329871-ab2ac55d-98e9-4e02-a734-58b8fb843f6e.png)



![image](https://user-images.githubusercontent.com/69936558/232456782-b59d7432-f290-4821-82bc-c5b756a8d9b8.png)
But my Steam app can show foreign languages properly.

**Comment by benkei-kuruma** [comment]
Still no fix for this?

**Comment by 22p** [comment]
> Still no upstream fix for this?

Fixed, need to refresh font cache
`flatpak run  --command=fc-cache com.google.Chrome -f -v`

**Comment by benkei-kuruma** [comment]
Thank you! 

Several other flatpaks, namely Steam in my case, are still having this issue. I hope those can get fixed eventually too.

**Comment by dogtopus** [comment]
Slightly non-intrusive workaround: Download "All Static Language Specific OTCs" from https://github.com/notofonts/noto-cjk/releases, extract it to `~/.var/com.valvesoftware.Steam/data/fonts`.
